## Data Analaysis

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("Mall_Customers.csv")

In [6]:
df.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [7]:
df.tail()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [8]:
print("Rows,Columns :",df.shape)

Rows,Columns : (200, 5)


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [10]:
df.describe()

CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [11]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

## k-means clustering

In [13]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [14]:
X=df[['Annual Income (k$)','Spending Score (1-100)']]  #Two columns required for clustering
X

Annual Income (k$)  Spending Score (1-100)
0                    15                      39
1                    15                      81
2                    16                       6
3                    16                      77
4                    17                      40
..                  ...                     ...
195                 120                      79
196                 126                      28
197                 126                      74
198                 137                      18
199                 137                      83

[200 rows x 2 columns]

In [15]:
from sklearn.cluster import KMeans

In [16]:
k_means=KMeans() 
k_means.fit(X)

KMeans()

In [17]:
k_means=KMeans()         #n_clusters by default=8
k_means.fit_predict(X)

array([1, 3, 5, 3, 1, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 1, 3, 1, 3, 1, 3,
       5, 3, 5, 3, 1, 3, 1, 3, 5, 3, 5, 3, 5, 3, 5, 3, 1, 3, 1, 3, 1, 7,
       1, 7, 7, 7, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 2, 2, 7, 7, 7, 7,
       7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 2, 6, 2, 6, 4, 6, 4, 6,
       2, 6, 4, 6, 4, 6, 4, 6, 4, 6, 2, 6, 4, 6, 2, 6, 4, 6, 4, 6, 4, 6,
       4, 6, 4, 6, 4, 6, 2, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6, 4, 6,
       4, 6, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0,
       4, 0])

**Elbow method to find number of clusters**

In [19]:
#WCSS matrix
wcss=[]
for i in range (1,11):
    k_means=KMeans(n_clusters=i)
    k_means.fit(X)
    wcss.append(k_means.inertia_)

In [35]:
wcss  #within cluster sum of squares


[269981.28000000014,
 184131.8850278851,
 106348.37306211119,
 73679.78903948837,
 44454.47647967972,
 38797.9027638142,
 31676.36973205365,
 29996.498093275768,
 28808.588195397482,
 19664.68519600554]

In [39]:
import matplotlib.pyplot as plt

In [43]:
plt.plot(range(1,11),wcss)
plt.title("Elbow Method")
plt.xlabel("Number of clusters")
plt.ylabel("WCSS")
plt.show()

## Model training

In [46]:
X=df[['Annual Income (k$)','Spending Score (1-100)']]  #Two columns required for clustering
X

Annual Income (k$)  Spending Score (1-100)
0                    15                      39
1                    15                      81
2                    16                       6
3                    16                      77
4                    17                      40
..                  ...                     ...
195                 120                      79
196                 126                      28
197                 126                      74
198                 137                      18
199                 137                      83

[200 rows x 2 columns]

In [48]:
k_means=KMeans(n_clusters=5,random_state=42) 
y_means=k_means.fit_predict(X)
y_means

array([4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2,
       4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 0,
       4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 1, 3, 1, 3, 1,
       0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1])

In [68]:
plt.scatter(X.iloc[y_means==0,0],X.iloc[y_means==0,1],s=100,c="red",label="Cluster_1")
plt.scatter(X.iloc[y_means==1,0],X.iloc[y_means==1,1],s=100,c="yellow",label="Cluster_2")
plt.scatter(X.iloc[y_means==2,0],X.iloc[y_means==2,1],s=100,c="green",label="Cluster_3")
plt.scatter(X.iloc[y_means==3,0],X.iloc[y_means==3,1],s=100,c="blue",label="Cluster_4")
plt.scatter(X.iloc[y_means==4,0],X.iloc[y_means==4,1],s=100,c="pink",label="Cluster_5")
plt.scatter(k_means.cluster_centers_[:,0],k_means.cluster_centers_[:,1],c="black")
plt.title("Customer Segmentation")
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.legend()
plt.show()

In [72]:
k_means.predict([[80,20]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


array([3])

## Saving the model

In [75]:
import joblib
joblib.dump(k_means,"Customer_Segmentation")

['Customer_Segmentation']

In [77]:
model=joblib.load("Customer_Segmentation")

In [79]:
model.predict([[20,20]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


array([4])